name: Daily Number Search

on:
  schedule:
    - cron: '0 1 * * *'  # 1am AEST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name "webdev-joe"
          git add docs/available_numbers.json
          git commit -m "Update available_numbers.json from workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/webdev-joe/auto-number-search.git
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

